#include "AgentRankRegistry.h"
#include <iostream>
#include <sstream>
#include <filesystem>
#include <fstream>
#include <cstdlib>
#include <algorithm>
#include <stdexcept>
#include "nlohmann/json.hpp"

AgentRankRegistry::AgentRankRegistry() {
    MPI_Comm_rank(MPI_COMM_WORLD, &m_localRank);
    m_simulationRank = 0;
}

void AgentRankRegistry::initializeFromConfig(const pugi::xml_node& config) {
    auto mpiConfig = config.child("MPIConfiguration");
    if (!mpiConfig.empty()) {
        m_simulationRank = mpiConfig.child("SimulationRank").text().as_int(0);
        std::string agentRanksStr = mpiConfig.child("AgentRanks").text().as_string();
        std::stringstream ss(agentRanksStr);
        std::string rank;
        while (std::getline(ss, rank, ',')) {
            m_agentRanks.insert(std::stoi(rank));
        }
    }
    if (m_localRank == m_simulationRank) {
        parseCoreRankConfig(config);
    }
    parseAgentRankConfig(config);
    parseCrossAgentRankConfig(config);
    
    std::cout << "AgentRankRegistry initialized for rank " << m_localRank << std::endl;
}
void AgentRankRegistry::parseCrossAgentRankConfig(const pugi::xml_node& config) {
    std::set<int> allowed;
    if (auto mpiCfg = config.child("MPIConfiguration")) {
        std::string crossStr = mpiCfg.child("CrossAgentRanks").text().as_string();
        if (!crossStr.empty()) {
            std::stringstream ss(crossStr);
            std::string item;
            while (std::getline(ss, item, ',')) {
                if (!item.empty()) {
                    try { allowed.insert(std::stoi(item)); } catch (...) {}
                }
            }
        }
    }
    if (allowed.empty()) {
        return;
    }

    // Prefer explicit per-epoch assignment mapping generated by DistributedMain:
    // data/agent_outputs/Topology/assignment_<date>.json
    //
    // Baseline mode: DESMAR_BASELINE=1 disables migration and therefore must ignore assignment_<date>.json,
    // falling back to static XML mapping.
    auto envBoolStrict = [](const char* name, bool defVal) -> bool {
        const char* v = std::getenv(name);
        if (!v || !*v) return defVal;
        std::string s(v);
        std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
        if (s == "true") return true;
        if (s == "false") return false;
        throw std::runtime_error(std::string("Environment variable ") + name +
                                 " must be 'true' or 'false' (got '" + s + "')");
    };
    const bool baselineEnv = envBoolStrict("DESMAR_BASELINE", false);
    const bool ignoreAssignment = baselineEnv;
    std::string simDate = config.attribute("date").as_string();
    bool loadedAssignment = false;
    nlohmann::json assignment;
    if (!ignoreAssignment && !simDate.empty()) {
        try {
            std::filesystem::path p = std::filesystem::path("data") / "agent_outputs" / "Topology" / (std::string("assignment_") + simDate + ".json");
            if (std::filesystem::exists(p)) {
                std::ifstream ifs(p);
                if (ifs.is_open()) {
                    std::stringstream ss; ss << ifs.rdbuf();
                    assignment = nlohmann::json::parse(ss.str(), nullptr, /*allow_exceptions=*/false);
                    if (!assignment.is_discarded() && assignment.is_object() && assignment.contains("agents") && assignment["agents"].is_object()) {
                        loadedAssignment = true;
                    }
                }
            }
        } catch (...) {
            loadedAssignment = false;
        }
    }

    for (auto crossRank : config.children("CrossAgentRank")) {
        int rank = crossRank.attribute("rank").as_int();
        if (allowed.find(rank) == allowed.end()) {
            continue;
        }
        m_crossAgentRanks.insert(rank);
        std::string routerName = crossRank.attribute("routerName").as_string();
        if (!routerName.empty()) { registerLocalAgent(routerName, rank); }
    }

    if (loadedAssignment) {
        for (auto it = assignment["agents"].begin(); it != assignment["agents"].end(); ++it) {
            if (!it.value().is_number_integer()) continue;
            int r = it.value().get<int>();
            if (allowed.find(r) == allowed.end()) continue;
            registerLocalAgent(it.key(), r);
        }
        std::cout << "[AgentRankRegistry] loaded cross-rank assignment for date=" << simDate << std::endl;
        return;
    }

    // Fallback: original XML range registration (only used when assignment file is missing)
    for (auto crossRank : config.children("CrossAgentRank")) {
        int rank = crossRank.attribute("rank").as_int();
        if (allowed.find(rank) == allowed.end()) continue;
        for (auto n : crossRank.children("DataFactoryAgents")) {
            int count = n.attribute("count").as_int();
            int startIndex = n.attribute("startIndex").as_int(1);
            registerAgentRange("CppDataFactoryAgent", startIndex, count, rank);
        }
        for (auto n : crossRank.children("CrossBehavioralSPTAgents")) {
            int count = n.attribute("count").as_int();
            int startIndex = n.attribute("startIndex").as_int(1);
            registerAgentRange("CppCrossBehavioralSPTAgent", startIndex, count, rank);
        }
        for (auto n : crossRank.children("CrossRLAgents")) {
            int count = n.attribute("count").as_int();
            int startIndex = n.attribute("startIndex").as_int(1);
            registerAgentRange("CppCrossRLAgent", startIndex, count, rank);
        }
        for (auto n : crossRank.children("CrossTestAgents")) {
            int count = n.attribute("count").as_int();
            int startIndex = n.attribute("startIndex").as_int(1);
            registerAgentRange("CppCrossTestAgent", startIndex, count, rank);
        }
    }
}

void AgentRankRegistry::parseCoreRankConfig(const pugi::xml_node& config) {
    auto coreRank = config.child("CoreRank");
    if (!coreRank.empty()) {
        for (auto exchange : coreRank.children("ExchangeAgent")) {
            std::string name = exchange.attribute("name").as_string();
            registerLocalAgent(name, m_simulationRank);
        }
        for (auto agent : coreRank.children()) {
            std::string nodeName = agent.name();
            if (nodeName != "ExchangeAgent") {
                std::string name = agent.attribute("name").as_string();
                if (!name.empty()) {
                    registerLocalAgent(name, m_simulationRank);
                }
            }
        }
    }
}

void AgentRankRegistry::parseAgentRankConfig(const pugi::xml_node& config) {
    for (auto agentRank : config.children("AgentRank")) {
        int rank = agentRank.attribute("rank").as_int();
        std::string routerName = agentRank.attribute("routerName").as_string();
        
        if (!routerName.empty()) {
            registerLocalAgent(routerName, rank);
        }
        
        for (auto noiseAgents : agentRank.children("NoiseAgents")) {
            int count = noiseAgents.attribute("count").as_int();
            int startIndex = noiseAgents.attribute("startIndex").as_int(1);
            registerAgentRange("CppNoiseAgent", startIndex, count, rank);
        }
        
        for (auto momentumAgents : agentRank.children("MomentumAgents")) {
            int count = momentumAgents.attribute("count").as_int();
            int startIndex = momentumAgents.attribute("startIndex").as_int(1);
            registerAgentRange("CppMomentumAgent", startIndex, count, rank);
        }
        
        for (auto hblAgents : agentRank.children("HeuristicBeliefLearningAgents")) {
            int count = hblAgents.attribute("count").as_int();
            int startIndex = hblAgents.attribute("startIndex").as_int(1);
            registerAgentRange("CppHeuristicBeliefLearningAgent", startIndex, count, rank);
        }
        
        for (auto mmAgents : agentRank.children("MarketMakerAgents")) {
            int count = mmAgents.attribute("count").as_int();
            int startIndex = mmAgents.attribute("startIndex").as_int(1);
            registerAgentRange("CppMarketMakerAgent", startIndex, count, rank);
        }

        for (auto testAgents : agentRank.children("TestAgents")) {
            int count = testAgents.attribute("count").as_int();
            int startIndex = testAgents.attribute("startIndex").as_int(1);
            registerAgentRange("CppTestAgent", startIndex, count, rank);
        }
    }
}

void AgentRankRegistry::registerLocalAgent(const std::string& agentName, int rank) {
    m_localAgentToRank[agentName] = rank;
    m_rankToAgents[rank].push_back(agentName);
    
    size_t underscorePos = agentName.find('_');
    if (underscorePos != std::string::npos) {
        std::string prefix = agentName.substr(0, underscorePos);
        addPrefixMapping(prefix, rank);
    }
    
    std::cout << "Registered local agent: " << agentName << " -> rank " << rank << std::endl;
}

void AgentRankRegistry::registerAgentRange(const std::string& agentType, int startIndex, 
                                          int count, int targetRank) {
    int endIndex = startIndex + count - 1;
    
    m_agentRanges.emplace_back(agentType, startIndex, endIndex, targetRank);
    int rangeIndex = static_cast<int>(m_agentRanges.size()) - 1;
    
    m_typeToRangeIndices[agentType].push_back(rangeIndex);
    
    addPrefixMapping(agentType, targetRank);
    
    std::cout << "Registered agent range: " << agentType 
              << " [" << startIndex << "-" << endIndex << "] -> rank " << targetRank << std::endl;
}

void AgentRankRegistry::addPrefixMapping(const std::string& prefix, int rank) {
    m_prefixToRanks[prefix].insert(rank);
}

AgentRankRegistry::ParsedAgentName AgentRankRegistry::parseAgentName(const std::string& agentName) const {
    ParsedAgentName result;
    result.isValid = false;
    
    size_t lastUnderscorePos = agentName.find_last_of('_');
    if (lastUnderscorePos == std::string::npos) {
        return result;
    }
    
    result.type = agentName.substr(0, lastUnderscorePos);
    std::string indexStr = agentName.substr(lastUnderscorePos + 1);
    
    try {
        result.index = std::stoi(indexStr);
        result.isValid = true;
    } catch (const std::exception&) {
        result.isValid = false;
    }
    
    return result;
}

int AgentRankRegistry::getAgentRank(const std::string& agentName) const {
    auto localIt = m_localAgentToRank.find(agentName);
    if (localIt != m_localAgentToRank.end()) {
        return localIt->second;
    }
    
    ParsedAgentName parsed = parseAgentName(agentName);
    if (!parsed.isValid) {
        return -1;
    }
    
    auto typeIt = m_typeToRangeIndices.find(parsed.type);
    if (typeIt == m_typeToRangeIndices.end()) {
        return -1;
    }
    
    for (int rangeIndex : typeIt->second) {
        const AgentRangeInfo& range = m_agentRanges[rangeIndex];
        if (range.containsIndex(parsed.index)) {
            return range.rank;
        }
    }
    
    return -1;
}

std::set<int> AgentRankRegistry::getTargetRanks(const std::string& target) const {
    std::set<int> ranks;
    
    if (target == "*") {
        ranks.insert(m_simulationRank);
        ranks.insert(m_agentRanks.begin(), m_agentRanks.end());
    }
    else if (target.back() == '*') {
        std::string prefix = target.substr(0, target.length() - 1);
        auto it = m_prefixToRanks.find(prefix);
        if (it != m_prefixToRanks.end()) {
            ranks = it->second;
        }
    }
    else {
        int rank = getAgentRank(target);
        if (rank != -1) {
            ranks.insert(rank);
        }
    }
    
    return ranks;
}

bool AgentRankRegistry::isLocalAgent(const std::string& agentName) const {
    return getAgentRank(agentName) == m_localRank;
}

void AgentRankRegistry::printRegistry() const {
    std::cout << "=== Agent Rank Registry ===" << std::endl;
    std::cout << "Local Rank: " << m_localRank << std::endl;
    std::cout << "Simulation Rank: " << m_simulationRank << std::endl;
    
    std::cout << "Local agents:" << std::endl;
    for (const auto& pair : m_localAgentToRank) {
        std::cout << "  " << pair.first << " -> rank " << pair.second << std::endl;
    }
    
    std::cout << "Distributed agent ranges:" << std::endl;
    for (const auto& range : m_agentRanges) {
        std::cout << "  " << range.agentType << " [" << range.startIndex
                  << "-" << range.endIndex << "] -> rank " << range.rank << std::endl;
    }
    
    std::cout << "Prefix mappings:" << std::endl;
    for (const auto& pair : m_prefixToRanks) {
        std::cout << "  " << pair.first << "* -> ranks [";
        for (int rank : pair.second) {
            std::cout << rank << " ";
        }
        std::cout << "]" << std::endl;
    }
}

std::vector<std::string> AgentRankRegistry::getLocalAgents() const {
    auto it = m_rankToAgents.find(m_localRank);
    return (it != m_rankToAgents.end()) ? it->second : std::vector<std::string>();
}